### ISSUE TITLE
Incorporate feedback and finalize report

### ISSUE THREAD

**Issue by chrismostert** [chrismostert/Search-r#22]
Incorporate the feedback from the intermediate report submission for the final deadline (12/03)

- [x] 1. Try to sharpen the introduction. It is unclear which research question the paper you reproduce poses. Everything is vaguely about time pressure but the reader does not learn what specific question(s) you are investigating. Also, make it very clear what the findings in prior works were - did users/participants _perceive_ their performance as lower or _was_ their performance lower according to objective metrics (and if not, it is also worth to mention).

- [x] 2. You are _reproducing_ the work, not _replicating_ it. Please check the ACM guidelines for replication vs. reproduction. 

- [x] 3. The background section will also benefit from sharpening the text, e.g. it now says "They found that time pressure has a significant impact on search behavior. More queries are sent to the search engine, fewer documents are viewed per query and less time is used to examine documents." It is unclear (1) which conditions were compared (where any conditions compared?) and (2) who sent more queries to the search engine - participants under time pressor or those not under time pressure? If I assume that under time pressure more queries are "sent to the search engine" then doesn't that contradict the findings of Liu and Wei which find "fewer queries" to be generated? If there is a contradiction, make sure to point out this difference with a potential explanation. I also recommend to create something like an overview table for Section 2 which shows off the most important dimensions of the papers you discuss here (e.g. number of participants, search system, major finding ...). 

- [x] 4. In the approach section I would expect first a concise/short overview of the original paper's setup. Maybe in the form of a diagram (text is fine too). You then only need to point out where you differ in your reproduction compared to the original paper (is your corpus the same? the task? the chosen topics? IR toolkit? retrieval model?). At the moment these differences are sprinkled throughout the section. It is better to keep them together. If you have not covered the research questions of the original paper in the introduction, at the very latest in this section you need to mention them.

- [x] 5. "Thus, the decision was made to index the entire corpus to more closely resemble a typical web search scenario in which false positive results are also returned." --> in IR we don't talk about false positives, just relevant and non-relevant documents.

- [x] 6. " When indexing the entire corpus the search results will more closely resemble the general web search scenario" --> this is quite a statement. Aquaint is a very small and clean collection, very different from the web. I'd be careful here.

- [x] 7. The number of relevant documents you report for each of the topics are wrong!! You are reporting here the number of JUDGED documents (remember TREC depth pooling), only those documents that have a judgment score of 1 or 2 are RELEVANT, every judged document with a score of 0 is NONRELEVANT!

- [ ] 8. The time pressure description is quite hidden in your long approach section - use subsections to make it easier for the reader to see what is going on where. How you implemented time pressure definitely deserves its own subsection. Unclear to me from the time pressure description: what happens after the 5 minutes are up? Will the participants have to stop?

- [x] 9. The Latin square rotation description is a bit of an overkill description if you only have 2 topics per participant. You can keep it in, but it doesn't add much value here.

- [x] 10. If I remember correctly you are using snippets only and clicks on the snippets to let participants indicate a positive judgment. Make sure to discuss this - is it important that participants cannot view the actual document? 

Well done so far, looking forward to reading the final report!

**Comment by MarkHaakman** [comment]
@jeroeness Can you fix the remaining points?
